name: Saucedemo testing
on:
    push:
        branches:
            - main

    repository_dispatch:
        types: [saucedemo_main]

    schedule:
        - cron: '0 6 * * *'

concurrency: saucedemo_main

jobs:
    mobile_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  architecture: x64
                  cache: maven

            - name: Run tests
              run: mvn test
